import type { Task, TaskContextSnapshot } from "./types.js";

const MAX_SERIALIZED_CONTEXT_BYTES = 32 * 1024;

export interface BriefingEngineInput {
  task: Task;
  context: TaskContextSnapshot;
}

export class BriefingEngine {
  renderBriefing(input: BriefingEngineInput): string {
    const { task, context } = input;

    return [
      `REQUEST SUMMARY\n${context.requestSummary}`,
      `STEP ID / TITLE\n${task.step}`,
      "WHY THIS STEP EXISTS\nAdvance current plan execution with typed orchestration context.",
      `TASK\n${task.brief}`,
      `CURRENT STATE\n${serializeValue(context.currentState)}`,
      "PLAN CONTEXT\n- Generated by AAS orchestration core",
      `CONTEXT\n- Previous work\n${context.previousWork || "None"}`,
      `FILES IN SCOPE\n- Create: ${formatFiles(context.filesToCreate)}\n- Modify: ${formatFiles(context.filesToModify)}`,
      "CONSTRAINTS\n- Follow repository conventions and security controls",
      "SUCCESS CRITERIA\n- Task completes with valid terminal payload",
      "VERIFICATION TARGET\n- Typed execution status reaches completed",
      "REFERENCE\n- .opencode/plans/current-plan.md",
      "DO NOT\n- Bypass security checks\n- Skip quality gates\n- Use untrusted script paths",
      "EXPECTED OUTPUT FORMAT\nFILES CHANGED + ASSUMPTIONS MADE + VALIDATION RUN + RISKS",
    ].join("\n\n");
  }
}

function formatFiles(files: string[]): string {
  if (files.length === 0) {
    return "None";
  }

  return files.join(", ");
}

function serializeValue(value: Record<string, unknown>): string {
  const serialized = JSON.stringify(value, null, 2);
  if (!serialized) {
    return "{}";
  }

  if (Buffer.byteLength(serialized, "utf8") <= MAX_SERIALIZED_CONTEXT_BYTES) {
    return serialized;
  }

  const truncated = serialized.slice(0, MAX_SERIALIZED_CONTEXT_BYTES);
  return `${truncated}\n... [truncated: context exceeds ${MAX_SERIALIZED_CONTEXT_BYTES} bytes]`;
}
